verify_exists not present in 1.5
URLField options 'verify_exists' doesn't exist anymore for django 1.5.
Remote it from publication model or you get this:

$ python manage.py syncdb
TypeError: __init__() got an unexpected keyword argument 'verify_exists'